### ISSUE TITLE
SD Turbo scheduler support

### ISSUE THREAD

**Issue by tastez** [Haoming02/comfyui-diffusion-cg#1]
Hi thank you for the great work and article. Trying this out with SDXL Turbo and its working fine but without SD Turbo scheduler support its worse than expected.

sd turbo workflow is to use these nodes
![image](https://github.com/Haoming02/comfyui-diffusion-cg/assets/78642112/bc7f2c07-57f4-48d7-af86-64fee1b615dd)

**Comment by Haoming02** [comment]
Arrr...
I knew Issue like this would happen. `ComfyUI` doesn't provide an easy way to hook the Callback, at least that I know of. So if I were to support it, I will need to copy the entire script just to change 1 line, for every new Sampler in the future...

**TL;DR:** Not planning to support it, until `ComfyUI` adds a way to hook callbacks.

**Comment by Haoming02** [comment]
I've rewritten the entire extension
It should work with the **SamplerCustom** now in the latest commit [f1fd309](https://github.com/Haoming02/comfyui-diffusion-cg/commit/f1fd309c04d7faf2233a25181308acedf3f0810f)~

**Comment by tastez** [comment]
nice change but doesnt affect a lot of common samplers that are all the rage now for turbo and lcm which is unfortunate since this is quite interesting and looks good

**Comment by Haoming02** [comment]
Welp, that's truly unfortunate...
