### ISSUE TITLE
CMYK values

### ISSUE THREAD

**Issue by andupotorac** [Haoming02/comfyui-diffusion-cg#13]
Hi there. Shouldn't the values be between 0 and 100? For example - https://codepen.io/draber/pen/mdyYLNJ. Not sure how these values should be set as you have them now.

OR even better, could we instead provide a RGB hex code that you then change to CMYK?

**Comment by Haoming02** [comment]
1. The values set are the *average* of each channel, so everything should center at `0.0`. If you really want to use a 0 - 100 scale, then `0.0` means `50%` I guess.

2. The reason why it's CMYK is cause it's what each channel in **SD 1.5** checkpoint represents. If you want to use RGB, take a look at: https://github.com/pamparamm/ComfyUI-vectorscope-cc

**Comment by andupotorac** [comment]
Gotcha, thanks!
