### ISSUE TITLE
Recenter Node disables partial workflow reruns

### ISSUE THREAD

**Issue by HaydenReeve** [Haoming02/comfyui-diffusion-cg#14]
Hiya 👋

I was wondering if there is a simple way to prevent the entire graph from reloading when triggering a new workflow run if a Recenter node is present.

If you place a Recenter Node in your workflow and then run the same workflow twice, it will trigger a complete rerun rather than the partial rerun you might expect.

**Comment by Haoming02** [comment]
Updated

Originally put that there so that the Node values are always updated, but I guess it's not really needed.
