### ISSUE TITLE
general question - SD and 16 bit colorspace and beyond

### ISSUE THREAD

**Issue by tastez** [Haoming02/comfyui-diffusion-cg#4]
just wondering if you have explored high colordepth output from SD? From what i've seen we can save out only 8bit decodes

**Comment by Haoming02** [comment]
Why yes we [did](https://github.com/Haoming02/sd-webui-vectorscope-cc/issues/16)

**Comment by tastez** [comment]
aaaaaaaaaaaaaaaaaaaaa!!!!!!!!!!!!!!!!!!!
