### ISSUE TITLE
How plausible is a non-global recenter node?

### ISSUE THREAD

**Issue by HaydenReeve** [Haoming02/comfyui-diffusion-cg#8]
Hello 👋

Your research here has saved me an absolute headache and a half recently. I've found myself depending greatly on the Recenter node to clear out that richly coloured haze from some checkpoints.

The issue I've noticed is that you can completely swap workflows, and forget you had something enabled, and it still applies, despite being a totally different workflow.

Obviously, the solution would be to make the effect less-than-global, although that's much easier said than done.

Sadly I'm no richly eloquated python individual, and I'm still wrapping my head around ComfyUI's implementation. As a result, I'm turning to you for this question.

Cheers!

**Comment by Haoming02** [comment]
Due to how ComfyUI works, I don't have an idea. And I haven't bothered with ComfyUI lately.

So yeah...
